### ISSUE TITLE
mysql查询BUG

### ISSUE THREAD

**Issue by SpringStudent** [lets-blade/blade-jdbc#10]
我使用如下代码查询MySQL数据库失败

```java
List<TbUser> tbUsers = new TbUser().in("user_name",new ArrayList<>(usernames)).findAll();
```

**错误日志**

![image](https://user-images.githubusercontent.com/14833956/31582061-462c654a-b1ac-11e7-9a7b-7c993a1e7e72.png)

- blade-jdbc-0.2.2-beta
- mysql-connector-5.1.40
- 本地数据库版本为 5.5

**Comment by SpringStudent** [comment]
是jar包有BUG吗？

**Comment by biezhi** [comment]
我稍后将查看这个问题
