### ISSUE TITLE
有的时候（不定时的），查询数据库返回NULL

### ISSUE THREAD

**Issue by huuusome** [lets-blade/blade-jdbc#8]
AR.find(queryParam).first(User.class);
AR.find(queryParam).list(User.class);
我在执行查询时，经常有一段时间，突然查不到数据返回NULL，再过几个小时又正常了，数据库的记录都是有的，请帮忙分析一下这是什么问题。

就像昨天晚上，服务正常运行中，刷新一下，突然报了空指针异常，日志显示查询数据库返回NULL。过了一个半小时后，又恢复正常了，期间我什么都没操作。

（有时候重启服务也能恢复正常）

**Comment by biezhi** [comment]
新版本已解决
